package ch.n1b.eve.wt.rest;

/**
 * Created on 23.08.2014.
 *
 * @author Thomas
 */
public enum EveHeaders {
    EVE_ALLIANCEID,
    EVE_ALLIANCENAME,
    EVE_CHARID,
    EVE_CHARNAME,
    EVE_CONSTELLATIONID,
    EVE_CONSTELLATIONNAME,
    EVE_CORPID,
    EVE_CORPNAME,
    EVE_CORPROLE,
    EVE_REGIONID,
    EVE_REGIONNAME,
    EVE_SERVERIP,
    EVE_SHIPID,
    EVE_SHIPNAME,
    EVE_SHIPTYPEID,
    EVE_SHIPTYPENAME,
    EVE_SOLARSYSTEMID,
    EVE_SOLARSYSTEMNAME,
    EVE_STATIONID,
    EVE_STATIONNAME,
    EVE_TRUSTED;
}
